encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path('create', views.create, name='create'),
    path("random", views.random, name="random"),
    path('edit/<str:title>', views.edit, name='edit'),
    path("<str:title>", views.page, name="page")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from http.client import HTTPResponse
from django.shortcuts import render
import markdown2
import re
from . import util
from django import forms
from random import choice

class NewEntryForm(forms.Form):
    title = forms.CharField(
        widget=forms.TextInput(attrs={"style": "width: 100%;"}),
        label='Title')
    content = forms.CharField(
        widget=forms.Textarea(attrs={"style": "width: 100%;", 'rows': 5}),
        label='Content')

class EditEntryForm(forms.Form):

    def __init__(self, title, *args, **kwargs):
        super(EditEntryForm, self).__init__(*args, **kwargs)
        self.fields['content'] = forms.CharField(
            widget=forms.Textarea(attrs={"style": "width: 100%;", 'rows': 5}),
            label='Content',
            initial=util.get_entry(title))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def page(request, title):
    content = util.get_entry(title)
    return render(request, 'encyclopedia/page.html', {
        "title": title,
        "content": markdown2.markdown(content) if content else content
    })

def search(request):
    entries = [el.lower() for el in util.list_entries()]
    search_q = request.GET.get('q').lower()
    match_entries = []

    if search_q in entries:
        return page(request, search_q)
    
    for entry in entries:
        if re.search(search_q, entry):
            match_entries.append(entry)
    return render(request, 'encyclopedia/search.html', {
        "match_entries": match_entries,
        "search_q": search_q
    })

def create(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)

        if form.is_valid():
            entries = [el.lower() for el in util.list_entries()]
            title = form.cleaned_data["title"]
            if title.lower() not in entries:
                util.save_entry(title, form.cleaned_data["content"])
                return page(request, title)
            else:
                return render(request, 'encyclopedia/newpage_err.html')
        
    return render(request, 'encyclopedia/create.html', {
        "form": NewEntryForm()
    })

def edit(request, title):
    if request.method == "POST":
        form = EditEntryForm(request.POST, title)
        util.save_entry(title, request.POST.get('content'))
        return page(request, title)
    
    return render(request, 'encyclopedia/edit.html', {
        "title": title,
        "form": EditEntryForm(title)
    })


def random(request):
    title = choice(util.list_entries())
    return page(request, title)

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page 
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>
    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" class="button">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page 
{% endblock %}

{% block body %}
    <h1>Edit Page</h1>
    <h2>{{ title }}</h2>
    <form action="{% url 'encyclopedia:edit' title %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Save" class="button">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:page' entry %} ">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="GET">
                    <input class='search' type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage_err.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page Error
{% endblock %}

{% block body %}
    Error: This page already exists.
{% endblock %}

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {% if content %}
        <h1>{{ title }}</h1>
        {{ content |safe }}
        <a href="{% url 'encyclopedia:edit' title %}">Edit Page</a>
    {% else %}
        <h1>404 Page not found</h1>
    {% endif %}

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    search results
{% endblock %}

{% block body %}
    {% if match_entries %}
        <h1>Search results for "{{ search_q }}"</h1>
        <ul>
            {% for entry in match_entries %}
                <li><a href="{% url 'encyclopedia:page' entry %} ">{{ entry }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h1>No results found</h1>
    {% endif %}
    
{% endblock %}